// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP4iGooy-GXts9xVTq1ZMPKRAx8QPMUsw',
    appId: '1:199827803463:web:c910942f68a64c9d06d062',
    messagingSenderId: '199827803463',
    projectId: 'phonex-43d8c',
    authDomain: 'phonex-43d8c.firebaseapp.com',
    storageBucket: 'phonex-43d8c.appspot.com',
    measurementId: 'G-88GCBP023R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3NPTqylwG8hIOLlsWew_gpLX6PEV56jk',
    appId: '1:199827803463:android:53ed924fc98d2f9406d062',
    messagingSenderId: '199827803463',
    projectId: 'phonex-43d8c',
    storageBucket: 'phonex-43d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByw0k8T3G_umM5Cp65pqFXeLRbSoLFnqk',
    appId: '1:199827803463:ios:17ac4b558855654406d062',
    messagingSenderId: '199827803463',
    projectId: 'phonex-43d8c',
    storageBucket: 'phonex-43d8c.appspot.com',
    androidClientId: '199827803463-2huemq00qigfq94v3tvmvebp5nb68sm9.apps.googleusercontent.com',
    iosClientId: '199827803463-pdpf1ftpk8snd4q58gvciv988qij0n4l.apps.googleusercontent.com',
    iosBundleId: 'com.phonoi.phonoiApp',
  );
}
